version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hs-assets-admin
    pull_policy: if_not_present
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
